version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app

    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: react_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    stdin_open: true
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true