# =========================
# APP NODES (App1 + App2)
# =========================
- hosts: app
  become: true

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - docker.io
          - git
        state: present

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone project
      git:
        repo: "https://github.com/lgitacc01/timekeeping.git"
        dest: /root/timekeeping
        version: main
        force: yes

    # =========================
    # BUILD BACKEND
    # =========================
    - name: Build backend image
      command: docker build -t timekeeper-backend /root/timekeeping/backend

    - name: Remove old backend container
      ignore_errors: true
      command: docker rm -f backend

    - name: Run backend container
      command: >
        docker run -d
        --name backend
        -p 5000:5000
        timekeeper-backend

    # =========================
    # BUILD FRONTEND
    # =========================
    - name: Build frontend image
      command: docker build -t timekeeper-frontend /root/timekeeping/frontend

    - name: Remove old frontend container
      ignore_errors: true
      command: docker rm -f frontend

    - name: Run frontend container
      command: >
        docker run -d
        --name frontend
        -p 5173:5173
        timekeeper-frontend --host


# =========================
# LOAD BALANCER (NGINX)
# =========================
- hosts: lb
  become: true

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Load Balancer
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          upstream backend_pool {
              server APP1_IP:5000;
              server APP2_IP:5000;
              least_conn;
          }

          upstream frontend_pool {
              server APP1_IP:5173;
              server APP2_IP:5173;
          }

          server {
              listen 80;

              location /api/ {
                  proxy_pass http://backend_pool;
              }

              location / {
                  proxy_pass http://frontend_pool;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted