# ======================
# APP SERVERS (App1 + App2)
# ======================
- hosts: app
  become: true

  tasks:

    - name: Install Docker
      apt:
        name:
          - docker.io
        update_cache: yes
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull backend image
      command: docker pull yourdockerhub/timekeeper-backend:latest

    - name: Run backend container
      command: >
        docker run -d
        --name flask_backend
        -p 5000:5000
        yourdockerhub/timekeeper-backend:latest


# ======================
# LOAD BALANCER (NGINX)
# ======================
- hosts: lb
  become: true

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure LB
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          upstream backend_pool {
              server APP1_IP:5000;
              server APP2_IP:5000;
              least_conn;
          }

          server {
              listen 80;

              location /api/ {
                  proxy_pass http://backend_pool/;
              }

              location / {
                  proxy_pass http://APP1_IP:5173;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted