# =========================
# APP NODES (App1 + App2)
# =========================
- hosts: app
  become: true

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - docker.io
          - git
        state: present

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone project
      git:
        repo: "https://github.com/lgitacc01/timekeeping.git"
        dest: /root/timekeeping
        version: main
        force: yes

    # =========================
    # BUILD BACKEND
    # =========================
    - name: Build backend image
      command: docker build -t timekeeper-backend /root/timekeeping/backend

    - name: Remove old backend container
      ignore_errors: true
      command: docker rm -f backend

    - name: Run backend container
      command: >
        docker run -d
        --name backend
        -p 5000:5000
        timekeeper-backend

    # =========================
    # BUILD FRONTEND
    # =========================
    - name: Build frontend image
      command: docker build -t timekeeper-frontend /root/timekeeping/frontend

    - name: Remove old frontend container
      ignore_errors: true
      command: docker rm -f frontend

    - name: Run frontend container
      command: >
        docker run -d
        --name frontend
        -p 5173:5173
        timekeeper-frontend --host


# =========================
# LOAD BALANCER (NGINX)
# =========================
- hosts: lb
  become: true

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx Load Balancer
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          upstream backend {
              server {{ app1_ip }}:5000;
              server {{ app2_ip }}:5000;
          }

          server {
              listen 80;

              location / {
                  proxy_pass http://backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: yes

    - name: Test Nginx config
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted